[build]
  command = "pnpm install && pnpm build --filter=healthcare-app"
  publish = "apps/healthcare/.next"

[build.environment]
  NODE_VERSION = "18"

[[plugins]]
  package = "@netlify/plugin-nextjs" 