[build]
  command = "pnpm install && pnpm build"

[build.environment]
  NODE_VERSION = "18"

# Required environment variables (set in Netlify dashboard):
# - NEXT_PUBLIC_NOVU_APPLICATION_IDENTIFIER
# - NOVU_SECRET_KEY

[[plugins]]
  package = "@netlify/plugin-nextjs" 